### ISSUE TITLE
 BiocParallel errors: Index out of range - AberrantExpression

### ISSUE THREAD

**Issue by KuechlerO** [gagneurlab/drop#308]
Hey guys, it's me again :D

Ok, so I'm trying to run the workflow with the additional external count-files.
However, once again I'm struggling.

My initial command is `snakemake aberrantExpression`, which leads also to several executions of the rule `AberrantExpression_pipeline_Counting_mergeCounts_R`.
But in my case it crashes when it tries to handle the external count samples.

*Error:*
```
Fehler: BiocParallel errors
  1 remote errors, element index: 16
  0 unevaluated and other errors
  first remote error: Indizierung außerhalb der Grenzen     # in English: Index out of range
```

*Context*: 
I utilized [this external count database](https://zenodo.org/record/4646823#.YivXyLgxlpQ) and included the emphasized [GTF file from release 34 of GENCODE](https://www.gencodegenes.org/human/release_34).
But now I really have no clue, what could cause the error...

To provide all necessary information, I attached the following files to this issue (as txt-files due to github restrictions):
1. [full workflow-logging](https://github.com/gagneurlab/drop/files/8236368/log-file.txt)
2. [log of specific rule that failed - "AberrantExpression_pipeline_Counting_mergeCounts_R"](https://github.com/gagneurlab/drop/files/8236369/rule_detail_log.txt)
3. [sample-annotation file as txt-file](https://github.com/gagneurlab/drop/files/8236403/sample_annotation_all.txt)
4. [config-file as txt-file](https://github.com/gagneurlab/drop/files/8236373/config.txt)

Looking forward to your insights! :)

**Comment by vyepez88** [comment]
Hi,
This is indeed a bug that we found recently. We fixed it and it's now available in the latest DROP version (1.1.3). Simply reinstall DROP in your conda environment, do `drop --version` to double-check if you have the latest one. Then on the repository where you're running DROP do: `drop update`. Afterwards, rerun the pipeline.

**Comment by KuechlerO** [comment]
@vyepez88 Thank you very much for the fast response.

Unfortunately, this did not change anything for me.
My version is already up-to-date (1.1.3) and also executing `drop update` before running the pipeline did not solve the issue.

Do you have further suggestions, how to solve this problem?

**Comment by KuechlerO** [comment]
Also this problem does only appear, when using the external counts. Without them, the workflow finishes without errors.

**Comment by nickhsmith** [comment]
~~could you please share the `output/processed_data/aberrant_expression/hg19_v34/params/merge/all_mergeParams.csv` file? It clearly seems there may have been another issue with the external counts.~~

Thank you for your patience and for helping us troubleshoot!

------
## EDIT
The reason is a documentation problem. The INDIVIDUAL_ID is not the same as the RNA_ID. 

Those seem swapped in your sample_annotation for the external counts. For example in `rule_detail_log.txt` (file no. 2) we see that the RNA_ID in the count file is `R98166`  but in your `sample_annotation.tsv` file that is listed as the INDIVIDUAL_ID. and instead you have the value `p51530` for the RNA_ID.

As a result it is looking for the ID `p51530` in the header of the count file, and not being able to. Fix that column (and double check the others) and you should be good to go!

We will work on the naming/documenting on our side.
Thanks again.

**Comment by KuechlerO** [comment]
Yes, your explanation is correct. I fixed it and finally got the desired results.
Many thanks!
Looking forward to the next results of running now also the other pipeline modules.

P.S.: It's also super cool, that you guys respond so quickly. Keep up the good work! :)
